//! Ship a PUBLISHED version's client (core-v2 #742).
//!
//! 🔴 WHY THIS EXISTS. A module client used to live ONLY behind a live dev
//! tunnel: the platform's resolve() answered `not_dev_mode` for any install
//! pinned to a published version, and the dev artifact was bound to a session.
//! The consequence was not a missing convenience — an app that imports a module
//! client could never close its dev tunnel. kaohsiung-association imports
//! `@mirrorstack-ai/modules`, generated by `mirrorstack apps client install`, so
//! "tunnel closed, full end to end" was unreachable for it by construction.
//!
//! The deploy now uploads the SAME canonical artifact the dev tunnel publishes —
//! `dev::client::package_client`, reused deliberately rather than re-packed, so
//! a consumer cannot get different bytes depending on which path produced them.

use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{Context, Result, anyhow};
use reqwest::blocking::Client;

use crate::api::{self, ApiError};
use crate::commands::dev::client::package_client;
use crate::http;

const UPLOAD_TIMEOUT: Duration = Duration::from_secs(300);
const CODE_CLIENT_UNCONFIGURED: &str = "version_client_unsupported";

/// What happened to the version's client.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum VersionClientOutcome {
    /// Uploaded and promoted; a consumer can install it with no tunnel.
    Shipped { revision: String, size_bytes: i64 },
    /// The platform has no artifact storage wired (local prod-sim).
    StorageUnconfigured,
    /// This platform build predates the version-client routes.
    EndpointsMissing,
}

/// Where the module's built client lives.
///
/// 🔴 THE TWO ABSENCES ARE NOT THE SAME, exactly as for the web bundle. A module
/// with no `client/` directory declares no client and must deploy cleanly —
/// erroring there would break every module that has none. A module that HAS a
/// client project but nothing built is a different thing: its client would
/// silently not ship, and a consumer pinning that version would get
/// `not_published` forever. That one is fatal and names the directory.
pub(crate) fn locate(dir: &Path) -> Result<Option<PathBuf>> {
    let out = dir.join("client/dist");
    if out.is_dir() {
        return Ok(Some(out));
    }
    if !dir.join("client").is_dir() {
        return Ok(None);
    }
    Err(anyhow!(
        "no built client at {} — the module has a client project but nothing built it. A version records the client it was cut with, so deploying now would publish a version whose client can never be installed.",
        out.display()
    ))
}

/// Package the built client and ship it for `version_ref`.
pub(crate) fn ship(
    api_client: &Client,
    apps_base: &str,
    access_token: &str,
    module_id: &str,
    version_ref: &str,
    output_dir: &Path,
) -> Result<VersionClientOutcome> {
    // The SAME packer the dev tunnel uses. Reused rather than reimplemented so
    // the bytes a consumer installs cannot differ by which path produced them.
    let artifact = package_client(output_dir)
        .with_context(|| format!("package client at {}", output_dir.display()))?;

    let upload = match api::create_module_version_client_upload(
        api_client,
        apps_base,
        access_token,
        module_id,
        version_ref,
    ) {
        Ok(upload) => upload,
        Err(error) if storage_unconfigured(&error) => {
            return Ok(VersionClientOutcome::StorageUnconfigured);
        }
        Err(error) if endpoints_missing(&error) => {
            return Ok(VersionClientOutcome::EndpointsMissing);
        }
        Err(ApiError::Unauthenticated) => return Err(anyhow!("session expired")),
        Err(error) => return Err(anyhow!("{error}")),
    };

    // The presigned URL carries its own auth, so this PUT goes out on a client
    // with no bearer token and an upload-sized timeout.
    let upload_client = http::client(UPLOAD_TIMEOUT)?;
    let response = upload_client
        .put(&upload.url)
        .body(artifact.bytes.clone())
        .send()
        .context("upload module client")?;
    if !response.status().is_success() {
        return Err(anyhow!(
            "uploading the module client failed with HTTP {}",
            response.status()
        ));
    }

    match api::finalize_module_version_client(
        api_client,
        apps_base,
        access_token,
        module_id,
        version_ref,
    ) {
        Ok(client) => {
            // 🔴 THE SERVER'S DIGEST IS THE ONE THAT COUNTS, and comparing it to
            // ours is the only check that the bytes we packed are the bytes it
            // stored. A mismatch means something re-wrote the object between the
            // PUT and the finalize; a consumer would then pin a revision for
            // bytes we never built.
            if !client.sha256.is_empty() && client.sha256 != artifact.sha256 {
                return Err(anyhow!(
                    "the platform stored a different client than we uploaded (ours {}, theirs {}) — refusing to report a revision we cannot vouch for",
                    &artifact.sha256[..artifact.sha256.len().min(12)],
                    &client.sha256[..client.sha256.len().min(12)]
                ));
            }
            Ok(VersionClientOutcome::Shipped {
                revision: client.revision,
                size_bytes: client.size_bytes,
            })
        }
        Err(error) if storage_unconfigured(&error) => Ok(VersionClientOutcome::StorageUnconfigured),
        Err(error) if endpoints_missing(&error) => Ok(VersionClientOutcome::EndpointsMissing),
        Err(ApiError::Unauthenticated) => Err(anyhow!("session expired")),
        Err(error) => Err(anyhow!("{error}")),
    }
}

fn storage_unconfigured(error: &ApiError) -> bool {
    matches!(
        error,
        ApiError::Server { status: 501, code, .. } if code == CODE_CLIENT_UNCONFIGURED
    )
}

/// A platform that predates these routes answers 404 for the route itself.
fn endpoints_missing(error: &ApiError) -> bool {
    matches!(error, ApiError::Unexpected { status: 404, .. })
}
